import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { Finding, Severity } from '../models';
import { PocketBaseService } from '../services/pocketbase.service';

@Component({ selector: 'wg-findings', imports: [AppSidebarComponent, FormsModule, DatePipe], template: `
  <div class="app-layout"><wg-app-sidebar /><main class="app-main"><header class="app-header"><div><span class="app-breadcrumb">OBSERVE / FINDINGS</span><h1>Finding register</h1><p>Prioritized conclusions with confidence, retained evidence, and a concrete next action.</p></div><span class="system-state"><i></i>{{ findings().length }} retained</span></header>
  @if (error()) { <div class="error-banner"><strong>Findings unavailable</strong><span>{{ error() }}</span></div> }
  <section class="filter-bar"><label><span>Search</span><input [ngModel]="search()" (ngModelChange)="search.set($event)" placeholder="Service, asset, evidence…"></label><label><span>Severity</span><select [ngModel]="severity()" (ngModelChange)="severity.set($event)"><option value="all">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option><option value="info">Info</option></select></label><div class="filter-result">{{ filtered().length }} results</div></section>
  <section class="split-register"><div class="finding-register panel">@for (finding of filtered(); track finding.id) { <button type="button" class="register-row" [class.selected]="active()?.id === finding.id" (click)="selected.set(finding)"><span class="severity-mark" [attr.data-severity]="finding.severity"></span><span><strong>{{ finding.title }}</strong><small>{{ finding.asset }} · {{ finding.created | date:'MMM d, HH:mm' }}</small></span><span><b>{{ finding.confidence }}%</b><small>{{ finding.severity }}</small></span></button> } @empty { <div class="empty-state">No findings match this filter.</div> }</div>
  <aside class="panel finding-inspector">@if (active(); as finding) { <div class="inspector-head"><span class="severity-label" [attr.data-severity]="finding.severity">{{ finding.severity }}</span><span>{{ finding.status }}</span></div><h2>{{ finding.title }}</h2><p class="inspector-summary">{{ finding.summary }}</p><div class="confidence-bar"><span [style.width.%]="finding.confidence"></span></div><small>{{ finding.confidence }}% confidence · severity and confidence are independent</small><h3>Observed evidence</h3><ul class="evidence-list">@for (evidence of finding.evidence; track evidence) { <li>{{ evidence }}</li> }</ul><h3>Recommended action</h3><p>{{ finding.remediation || 'Review whether this public exposure is intended and reduce access when it is not.' }}</p><h3>Sources</h3>@if (finding.sourceUrls.length) { <div class="source-links">@for (url of finding.sourceUrls; track url) { <a [href]="url" target="_blank" rel="noopener">{{ host(url) }} ↗</a> }</div> } @else { <p class="unknown-copy">No external URL was required; evidence came from the direct observation.</p> } } @else { <div class="empty-state">Select a finding to inspect its evidence.</div> }</aside></section>
  </main></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class FindingsComponent implements OnInit {
  private readonly db = inject(PocketBaseService); protected readonly findings = signal<Finding[]>([]); protected readonly selected = signal<Finding | null>(null); protected readonly error = signal(''); protected readonly search = signal(''); protected readonly severity = signal<Severity | 'all'>('all');
  protected readonly filtered = computed(() => { const query = this.search().toLowerCase(); return this.findings().filter((f) => (this.severity() === 'all' || f.severity === this.severity()) && (!query || [f.title, f.asset, f.summary, ...f.evidence].join(' ').toLowerCase().includes(query))); });
  protected readonly active = computed(() => this.filtered().find((finding) => finding.id === this.selected()?.id) || this.filtered()[0] || null);
  ngOnInit(): void { void this.db.findings().then((v) => { this.findings.set(v); this.selected.set(v[0] || null); }).catch((e) => this.error.set(e instanceof Error ? e.message : 'Could not load findings.')); }
  protected host(url: string): string { try { return new URL(url).hostname; } catch { return url; } }
}
