import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { PublicIdentity, Target } from '../models';
import { PocketBaseService } from '../services/pocketbase.service';

@Component({ selector: 'wg-identities', imports: [AppSidebarComponent, FormsModule, DatePipe], template: `
  <div class="app-layout"><wg-app-sidebar /><main class="app-main identity-page"><header class="app-header"><div><span class="app-breadcrumb">OBSERVE / IDENTITY EXPOSURE</span><h1>Public identity ledger</h1><p>People and mailboxes explicitly returned by owned services—without profile guessing or social-network scraping.</p></div><label class="target-select"><span>Target</span><select [ngModel]="targetId()" (ngModelChange)="selectTarget($event)">@for (target of targets(); track target.id) { <option [value]="target.id">{{ target.hostname }}</option> }</select></label></header>
  @if (error()) { <div class="error-banner"><strong>Identity ledger unavailable</strong><span>{{ error() }}</span></div> }
  <section class="identity-summary panel"><div><span class="section-index">DIRECT PUBLIC EVIDENCE</span><strong>{{ identities().length }}</strong><small>unique records observed</small></div><div><strong>{{ needsReview() }}</strong><small>employment status unknown</small></div><p>These records show what a public service disclosed. They do not prove account access, administrator privileges, or present employment.</p></section>
  <section class="filter-bar"><label><span>Search evidence</span><input [ngModel]="search()" (ngModelChange)="search.set($event)" placeholder="Name, email, source asset…"></label><label><span>Status</span><select [ngModel]="status()" (ngModelChange)="status.set($event)"><option value="all">All records</option><option value="unknown">Needs review</option><option value="current">Confirmed current</option><option value="former">Confirmed former</option><option value="not_applicable">Not applicable</option></select></label><div class="filter-result">{{ filtered().length }} records</div></section>
  <section class="identity-layout"><div class="panel identity-register">@for (identity of filtered(); track identity.id) { <button type="button" class="identity-row" [class.selected]="active().id === identity.id" (click)="selectIdentity(identity)"><i>{{ identity.kind === 'mailbox' ? '@' : identity.kind === 'organization' ? '◇' : '◉' }}</i><span><strong>{{ identity.displayName || identity.email || 'Unnamed public identity' }}</strong><small>{{ identity.sourceAssetKey }}</small></span><span class="identity-status" [attr.data-status]="identity.employmentStatus">{{ statusLabel(identity.employmentStatus) }}</span></button> } @empty { <div class="empty-state"><strong>No public identity records retained.</strong><span>A new scan will add only identities directly returned by approved services or registries.</span></div> }</div>
  <aside class="panel identity-inspector">@if (active(); as identity) { <header><span class="source-glyph">{{ identity.kind === 'mailbox' ? '@' : '◉' }}</span><div><span class="section-index">{{ identity.kind }} · {{ identity.confidence }}% confidence</span><h2>{{ identity.displayName || identity.email }}</h2></div></header><dl class="fact-list"><div><dt>Email</dt><dd>{{ identity.email || 'Not publicly returned' }}</dd></div><div><dt>Source asset</dt><dd>{{ identity.sourceAssetKey }}</dd></div><div><dt>Observed</dt><dd>{{ identity.created | date:'medium' }}</dd></div><div><dt>Status</dt><dd>{{ statusLabel(identity.employmentStatus) }}</dd></div></dl><h3>Direct evidence</h3><ul class="evidence-list">@for (item of identity.evidence; track item) { <li>{{ item }}</li> }</ul><h3>Explicit links &amp; evidence sources</h3>@if (links(identity).length) { <div class="identity-links">@for (link of links(identity); track link) { <a [href]="link" target="_blank" rel="noopener noreferrer">{{ linkLabel(link) }} ↗</a> }</div> } @else { <p class="unknown-copy">No public profile link was explicitly returned. Wellguard will not guess one from a name.</p> }<h3>Owner review</h3>@if (db.isAdmin()) { <label class="review-field"><span>Employment relevance</span><select [(ngModel)]="reviewStatus"><option value="unknown">Unknown / review required</option><option value="current">Confirmed current</option><option value="former">Confirmed former</option><option value="not_applicable">Not applicable</option></select></label><label class="review-field"><span>Review note</span><textarea [(ngModel)]="reviewNote" maxlength="800" rows="3" placeholder="Owner-confirmed context; public absence alone is not proof."></textarea></label><button class="button primary compact" type="button" (click)="saveReview(identity)" [disabled]="saving()">{{ saving() ? 'Saving…' : 'Save owner review' }}</button> } @else { <p class="unknown-copy">Only a workspace administrator can confirm identity status.</p> } } @else { <div class="empty-state">Select a public identity record.</div> }</aside></section>
  </main></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class IdentitiesComponent implements OnInit {
  protected readonly db = inject(PocketBaseService); protected readonly targets = signal<Target[]>([]); protected readonly targetId = signal(''); protected readonly raw = signal<PublicIdentity[]>([]); protected readonly selected = signal<PublicIdentity | null>(null); protected readonly search = signal(''); protected readonly status = signal<PublicIdentity['employmentStatus'] | 'all'>('all'); protected readonly error = signal(''); protected readonly saving = signal(false); protected reviewStatus: PublicIdentity['employmentStatus'] = 'unknown'; protected reviewNote = '';
  protected readonly identities = computed(() => { const retained = new Map<string, PublicIdentity>(); for (const identity of this.raw()) if (!retained.has(identity.key)) retained.set(identity.key, identity); return [...retained.values()]; });
  protected readonly needsReview = computed(() => this.identities().filter((identity) => identity.employmentStatus === 'unknown').length);
  protected readonly filtered = computed(() => { const query = this.search().toLowerCase(); return this.identities().filter((identity) => (this.status() === 'all' || identity.employmentStatus === this.status()) && (!query || [identity.displayName, identity.email, identity.sourceAssetKey, ...identity.evidence].join(' ').toLowerCase().includes(query))); });
  protected readonly active = computed(() => this.filtered().find((identity) => identity.id === this.selected()?.id) || this.filtered()[0] || null);
  ngOnInit(): void { void this.db.targets().then((targets) => { this.targets.set(targets); this.targetId.set(targets[0]?.id || ''); return this.load(); }).catch((error) => this.error.set(error instanceof Error ? error.message : 'Could not load targets.')); }
  protected selectTarget(id: string): void { this.targetId.set(id); this.selected.set(null); void this.load(); }
  private async load(): Promise<void> { if (!this.targetId()) return; try { const items = await this.db.publicIdentities(this.targetId()); this.raw.set(items); this.selectForReview(items[0] || null); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Could not load public identities.'); } }
  protected statusLabel(status: PublicIdentity['employmentStatus']): string { return ({ unknown: 'Needs review', current: 'Current · owner confirmed', former: 'Former · owner confirmed', not_applicable: 'Not applicable' })[status]; }
  protected selectIdentity(identity: PublicIdentity): void { this.selectForReview(identity); }
  protected links(identity: PublicIdentity): string[] { return [...new Set([...identity.publicLinks, ...identity.sourceUrls])]; }
  protected linkLabel(link: string): string { try { const host = new URL(link).hostname.replace(/^www\./, ''); return host.includes('linkedin.com') ? 'LinkedIn · explicitly sourced' : host; } catch { return 'Public source'; } }
  protected async saveReview(identity: PublicIdentity): Promise<void> { this.saving.set(true); this.error.set(''); try { await this.db.reviewPublicIdentity(identity, this.reviewStatus, this.reviewNote.trim()); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Review could not be saved.'); } finally { this.saving.set(false); } }
  private selectForReview(identity: PublicIdentity | null): void { this.selected.set(identity); this.reviewStatus = identity?.employmentStatus || 'unknown'; this.reviewNote = identity?.reviewNote || ''; }
}
