import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ThemeService } from '../services/theme.service';

@Component({ selector: 'wg-landing', imports: [RouterLink], template: `
  <div class="landing-shell"><header class="public-nav wrap"><a class="wordmark" routerLink="/"><span class="brand-mark"><i></i></span><span>WELLGUARD<em>OBSERVE</em></span></a><nav><a href="#surface">Surface model</a><a href="#method">Method</a><a href="#boundaries">Boundaries</a></nav><div class="public-actions"><button class="icon-button theme-icon" type="button" (click)="theme.toggle()" aria-label="Toggle theme">{{ theme.theme() === 'dark' ? '☼' : '☾' }}</button><a class="button secondary compact" routerLink="/login">Private access →</a></div></header>
  <main><section class="saas-hero wrap"><div class="hero-copy"><div class="eyebrow"><span class="pulse-dot"></span>Agent-led external reconnaissance</div><h1>See your infrastructure from the <span>outside.</span></h1><p>Wellguard maps public services, follows identity clues, checks TLS and explains suspicious exposure—with the evidence and agent trace attached.</p><div class="hero-actions"><a class="button primary" routerLink="/app">Open live workspace <span>→</span></a><a href="#surface" class="button ghost">Explore the surface model</a></div><div class="trust-line"><span>AUTHORIZED TARGETS</span><span>NO EXPLOITATION</span><span>FULL TOOL TRACE</span></div></div>
    <div class="hero-console" aria-label="Example infrastructure exposure graph"><header><span><i></i>miroslav-petro.com</span><b>LIVE MODEL</b></header><div class="mini-map"><svg viewBox="0 0 760 370" preserveAspectRatio="none"><path d="M112 186 C180 186 196 104 266 104"/><path d="M336 104 C404 104 408 184 474 184"/><path d="M536 184 C594 184 600 102 658 102"/><path d="M536 184 C594 184 600 264 658 264"/></svg><div class="mini-node domain"><i>◎</i><span><strong>Domain</strong><small>authorized root</small></span></div><div class="mini-node edge"><i>◇</i><span><strong>Cloudflare</strong><small>public edge</small></span></div><div class="mini-node origin"><i>▣</i><span><strong>Origin</strong><small>concealed</small></span></div><div class="mini-node service healthy"><i>:</i><span><strong>443</strong><small>TLS valid</small></span></div><div class="mini-node service risk"><i>◆</i><span><strong>Easypanel</strong><small>review exposure</small></span><b>1</b></div></div><footer><span><i class="cyan"></i>Evidence observed</span><span><i class="red"></i>Needs action</span><strong>Click any node → evidence</strong></footer></div>
  </section>
  <section class="signal-bar"><div class="wrap"><span>EXTERNAL POSTURE <b>74 / 100</b></span><span>ASSETS MAPPED <b>4</b></span><span>HIGH PRIORITY <b class="risk-text">1</b></span><span>TLS <b class="good-text">VALID</b></span><span>TRACE <b>12 TOOL CALLS</b></span></div></section>
  <section class="product-section wrap" id="surface"><div class="section-copy"><span class="section-index">ONE CONNECTED PICTURE</span><h2>Ports are clues.<br>The topology is the answer.</h2><p>A flat scanner output makes you assemble the story yourself. Wellguard connects domains, edge providers, hidden origins, reachable ports and identified services—without pretending uncertain data is fact.</p></div><div class="capability-grid"><article><i>⌘</i><h3>Surface graph</h3><p>Follow exposure from public identity to service. Risk travels with the affected node.</p></article><article><i>△</i><h3>Evidence-backed findings</h3><p>Every conclusion carries confidence, raw observations, sources and a next action.</p></article><article><i>›_</i><h3>Transparent agent</h3><p>Inspect the model conversation, tool inputs and bounded outputs for every scan.</p></article><article><i>◉</i><h3>TLS & public intelligence</h3><p>Validate transport identity and corroborate exact versions with reliable sources.</p></article></div></section>
  <section class="workflow-section" id="method"><div class="wrap"><div class="section-copy"><span class="section-index">ADAPTIVE RECONNAISSANCE</span><h2>The next safe check follows the strongest evidence.</h2></div><div class="workflow"><article><span>01</span><h3>Establish identity</h3><p>DNS, certificate records, TLS and the public HTTP response create the first map.</p></article><article><span>02</span><h3>Investigate signals</h3><p>The agent chooses bounded port and service checks from what it actually observed.</p></article><article><span>03</span><h3>Corroborate</h3><p>Exact product or version clues are checked against public, authoritative sources.</p></article><article><span>04</span><h3>Explain action</h3><p>Risk, confidence, evidence and remediation remain connected in the report.</p></article></div></div></section>
  <section class="boundary-section wrap" id="boundaries"><div><span class="section-index">SECURE BY CONSTRAINT</span><h2>Curious inside a hard boundary.</h2><p>Wellguard is built for owners who want an outsider’s view without turning the product into a general-purpose scanner.</p></div><ul><li><i>✓</i>Verified or administrator-approved targets only</li><li><i>✓</i>Safe handshakes and read-only requests</li><li><i>✓</i>No credentials, payloads, exploitation, or evasion</li><li><i>✓</i>Private-address and redirect enforcement</li></ul></section>
  <section class="landing-cta"><div class="wrap"><div><span class="section-index">PRIVATE PREVIEW</span><h2>Your infrastructure is already describing itself.</h2></div><div><p>See the story an unauthenticated outsider can assemble.</p><a class="button primary" routerLink="/app">Open Wellguard Observe →</a></div></div></section></main>
  <footer class="public-footer wrap"><a class="wordmark" routerLink="/"><span class="brand-mark"><i></i></span><span>WELLGUARD<em>OBSERVE</em></span></a><p>External exposure intelligence for developers.</p><span>Reconnaissance only · 2026</span></footer></div>
`, changeDetection: ChangeDetectionStrategy.OnPush })
export class LandingComponent { protected readonly theme = inject(ThemeService); }
