import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { Finding, Scan, Target } from '../models';
import { PocketBaseService } from '../services/pocketbase.service';

@Component({ selector: 'wg-reports', imports: [AppSidebarComponent, DatePipe], template: `
  <div class="app-layout"><wg-app-sidebar /><main class="app-main"><header class="app-header"><div><span class="app-breadcrumb">OBSERVE / REPORTS</span><h1>Investigation reports</h1><p>Completed scan summaries, evidence-linked findings, and downloadable records.</p></div><button class="button secondary compact" type="button" (click)="print()">Print selected</button></header>
  @if (error()) { <div class="error-banner"><strong>Reports unavailable</strong><span>{{ error() }}</span></div> }
  <section class="reports-layout"><div class="panel report-list"><div class="panel-heading"><div><span class="section-index">SCAN HISTORY</span><h2>{{ scans().length }} reports</h2></div></div>@for (scan of scans(); track scan.id) { <button type="button" class="report-row" [class.selected]="selected()?.id === scan.id" (click)="selected.set(scan)"><span class="report-status" [attr.data-status]="scan.status">{{ scan.status === 'completed' ? '✓' : scan.status === 'failed' ? '!' : '…' }}</span><span><strong>{{ targetName(scan.target) }}</strong><small>{{ scan.startedAt | date:'MMM d, y · HH:mm:ss' }}</small></span><span><b>{{ findingCount(scan.id) }}</b><small>findings</small></span><span>→</span></button> } @empty { <div class="empty-state">No investigation reports have completed yet.</div> }</div>
  <article class="panel report-document" id="print-report">@if (selected(); as scan) { <header><div><span class="section-index">WELLGUARD OBSERVE / EXTERNAL RECON</span><h2>{{ targetName(scan.target) }}</h2></div><span class="report-id">{{ scan.id }}</span></header><div class="report-meta"><div><small>STATUS</small><strong>{{ scan.status }}</strong></div><div><small>STARTED</small><strong>{{ scan.startedAt | date:'medium' }}</strong></div><div><small>DURATION</small><strong>{{ duration(scan) }}</strong></div><div><small>FINDINGS</small><strong>{{ selectedFindings().length }}</strong></div></div><section><h3>Investigator summary</h3><p>{{ scan.summary || scan.error || 'No summary was retained.' }}</p></section><section><h3>Findings</h3>@for (finding of selectedFindings(); track finding.id) { <div class="report-finding"><span class="severity-label" [attr.data-severity]="finding.severity">{{ finding.severity }}</span><div><strong>{{ finding.title }}</strong><p>{{ finding.summary }}</p><small>{{ finding.asset }} · {{ finding.confidence }}% confidence</small></div></div> } @empty { <p class="unknown-copy">No findings are linked to this scan.</p> }</section><footer><span>Reconnaissance only · evidence retained</span><button class="button primary compact" type="button" (click)="export(scan)">Export JSON ↓</button></footer> } @else { <div class="empty-state">Select a scan to open its report.</div> }</article></section>
  </main></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class ReportsComponent implements OnInit {
  private readonly db = inject(PocketBaseService); protected readonly scans = signal<Scan[]>([]); protected readonly findings = signal<Finding[]>([]); protected readonly targets = signal<Target[]>([]); protected readonly selected = signal<Scan | null>(null); protected readonly error = signal(''); protected readonly selectedFindings = computed(() => this.findings().filter((f) => f.scan === this.selected()?.id));
  ngOnInit(): void { void Promise.all([this.db.scans(), this.db.findings(), this.db.targets()]).then(([scans, findings, targets]) => { this.scans.set(scans); this.findings.set(findings); this.targets.set(targets); this.selected.set(scans[0] || null); }).catch((e) => this.error.set(e instanceof Error ? e.message : 'Could not load reports.')); }
  protected targetName(id: string): string { return this.targets().find((t) => t.id === id)?.hostname || 'Unknown target'; }
  protected findingCount(id: string): number { return this.findings().filter((f) => f.scan === id).length; }
  protected duration(scan: Scan): string { const ms = Date.parse(scan.completedAt) - Date.parse(scan.startedAt); return Number.isFinite(ms) && ms >= 0 ? `${Math.round(ms / 1000)} sec` : '—'; }
  protected print(): void { window.print(); }
  protected export(scan: Scan): void { const payload = { product: 'Wellguard Observe', generatedAt: new Date().toISOString(), target: this.targetName(scan.target), scan, findings: this.selectedFindings() }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `wellguard-${this.targetName(scan.target)}-${scan.id}.json`; anchor.click(); URL.revokeObjectURL(url); }
}
