import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { ActivatedRoute } from '@angular/router';
import { AgentActionRecord, Finding, Scan, Target } from '../models';
import { PocketBaseService } from '../services/pocketbase.service';
import { ReportSummaryComponent } from '../components/report-summary.component';
import { FindingStoryComponent } from '../components/finding-story.component';

@Component({ selector: 'wg-reports', imports: [AppSidebarComponent, DatePipe, ReportSummaryComponent, FindingStoryComponent], template: `
  <div class="app-layout"><wg-app-sidebar /><main class="app-main"><header class="app-header"><div><span class="app-breadcrumb">OBSERVE / REPORTS</span><h1>Investigation reports</h1><p>Completed scan summaries, evidence-linked findings, and downloadable records.</p></div><button class="button secondary compact" type="button" (click)="print()">Print selected</button></header>
  @if (error()) { <div class="error-banner"><strong>Reports unavailable</strong><span>{{ error() }}</span></div> }
  <section class="reports-layout"><div class="panel report-list"><div class="panel-heading"><div><span class="section-index">SCAN HISTORY</span><h2>{{ scans().length }} reports</h2></div></div>@for (scan of scans(); track scan.id) { <button type="button" class="report-row" [class.selected]="selected()?.id === scan.id" (click)="selected.set(scan)"><span class="report-status" [attr.data-status]="scan.status">{{ scan.status === 'completed' ? '✓' : scan.status === 'failed' ? '!' : '…' }}</span><span><strong>{{ targetName(scan.target) }}</strong><small>{{ scan.startedAt | date:'MMM d, y · HH:mm:ss' }}</small></span><span><b>{{ findingCount(scan.id) }}</b><small>findings</small></span><span>→</span></button> } @empty { <div class="empty-state">No investigation reports have completed yet.</div> }</div>
  <article class="panel report-document" id="print-report">@if (selected(); as scan) { <header><div><span class="section-index">WELLGUARD OBSERVE / EXTERNAL RECON</span><h2>{{ targetName(scan.target) }}</h2></div><span class="report-id">{{ scan.id }}</span></header><div class="report-meta"><div><small>STATUS</small><strong>{{ scan.status }}</strong></div><div><small>STARTED</small><strong>{{ scan.startedAt | date:'medium' }}</strong></div><div><small>DURATION</small><strong>{{ duration(scan) }}</strong></div><div><small>FINDINGS</small><strong>{{ selectedFindings().length }}</strong></div></div><section><h3>Investigator summary</h3><wg-report-summary [text]="scan.summary || scan.error || 'No summary was retained.'" /></section><section><div class="report-section-heading"><h3>External verification coverage</h3><span>Execution evidence, not pass/fail</span></div><div class="coverage-grid">@for (control of coverage(); track control.id) { <article [attr.data-state]="control.observed ? 'observed' : 'untested'"><i>{{ control.observed ? '✓' : '—' }}</i><div><strong>{{ control.label }}</strong><span>{{ control.id }}</span><small>{{ control.observed ? control.evidence : 'Not exercised in this scan profile or investigation.' }}</small></div></article> }</div><p class="compliance-caveat">OWASP references describe testing and verification requirements. CRA references indicate potentially relevant evidence only; this report is not a conformity assessment or legal opinion.</p></section><section><h3>Findings</h3>@for (finding of selectedFindings(); track finding.id) { <div class="report-finding"><span class="severity-label" [attr.data-severity]="finding.severity">{{ finding.severity }}</span><div><strong>{{ finding.title }}</strong>@if (finding.weaknessIds.length || finding.cveIds.length || finding.frameworkRefs.length) { <div class="identifier-strip">@for (id of finding.weaknessIds; track id) { <span data-kind="cwe">{{ id }}</span> } @for (id of finding.cveIds; track id) { <span data-kind="cve">{{ id }}</span> } @for (reference of finding.frameworkRefs; track reference.control) { <a data-kind="framework" [href]="reference.url" target="_blank" rel="noopener">{{ reference.control }} ↗</a> }</div> }<p>{{ finding.summary }}</p><small>{{ finding.asset }} · {{ finding.confidence }}% confidence</small><wg-finding-story [finding]="finding" [compact]="true" /></div></div> } @empty { <p class="unknown-copy">No findings are linked to this scan.</p> }</section><footer><span>Authorized external evidence · bounded methods</span><button class="button primary compact" type="button" (click)="export(scan)">Export JSON ↓</button></footer> } @else { <div class="empty-state">Select a scan to open its report.</div> }</article></section>
  </main></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class ReportsComponent implements OnInit {
  private readonly db = inject(PocketBaseService); private readonly route = inject(ActivatedRoute); protected readonly scans = signal<Scan[]>([]); protected readonly findings = signal<Finding[]>([]); protected readonly targets = signal<Target[]>([]); protected readonly actions = signal<AgentActionRecord[]>([]); protected readonly selected = signal<Scan | null>(null); protected readonly error = signal(''); protected readonly selectedFindings = computed(() => this.findings().filter((f) => f.scan === this.selected()?.id));
  protected readonly coverage = computed(() => { const tools = new Set(this.actions().filter((action) => action.scan === this.selected()?.id).map((action) => action.tool)); return [
    { id: 'WSTG-SESS-02 · ASVS v5.0.0-3.3', label: 'Cookie attributes', observed: tools.has('inspect_browser_session_controls'), evidence: 'Cookie names and attributes observed without retaining or replaying values.' },
    { id: 'WSTG-CLNT-07 · ASVS v5.0.0-3.4.2', label: 'Cross-origin policy', observed: tools.has('inspect_browser_session_controls'), evidence: 'Fixed synthetic Origin compared without credentials.' },
    { id: 'WSTG-INPV-05 · ASVS v5.0.0-1.2.4', label: 'Input error handling', observed: tools.has('inspect_input_error_handling'), evidence: 'Three-request quoted-input differential; no SQL execution attempted.' },
    { id: 'ASVS v5.0.0-2.4.1 / 15.3.4', label: 'Throttle and proxy trust', observed: tools.has('inspect_rate_limit_controls'), evidence: 'Sequential capped burst; header comparison only after HTTP 429.' },
    { id: 'CWE-548 · CRA Annex I, Part I (2)(j)', label: 'Public directory indexes', observed: tools.has('inspect_public_directory_index'), evidence: 'One observed directory path checked; filenames retained without downloading an entry.' },
    { id: 'CRA Annex I, Part I (2)(j)', label: 'Public attack surface', observed: tools.has('discover_service_hosts') && (tools.has('inspect_safe_web_audit') || tools.has('inspect_reviewed_nuclei')), evidence: 'Service discovery and reviewed public exposure checks were retained.' }
  ]; });
  ngOnInit(): void { void Promise.all([this.db.scans(), this.db.findings(), this.db.targets(), this.db.agentActions()]).then(([scans, findings, targets, actions]) => { this.scans.set(scans); this.findings.set(findings); this.targets.set(targets); this.actions.set(actions); const targetId = this.route.snapshot.queryParamMap.get('target'); this.selected.set(scans.find((scan) => scan.target === targetId) || scans[0] || null); }).catch((e) => this.error.set(e instanceof Error ? e.message : 'Could not load reports.')); }
  protected targetName(id: string): string { return this.targets().find((t) => t.id === id)?.hostname || 'Unknown target'; }
  protected findingCount(id: string): number { return this.findings().filter((f) => f.scan === id).length; }
  protected duration(scan: Scan): string { const ms = Date.parse(scan.completedAt) - Date.parse(scan.startedAt); return Number.isFinite(ms) && ms >= 0 ? `${Math.round(ms / 1000)} sec` : '—'; }
  protected print(): void { window.print(); }
  protected export(scan: Scan): void { const payload = { product: 'Wellguard Observe', generatedAt: new Date().toISOString(), target: this.targetName(scan.target), scan, verificationCoverage: this.coverage(), findings: this.selectedFindings(), disclaimer: 'Framework mappings are evidence references, not certification, legal advice, or a CRA conformity assessment.' }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `wellguard-${this.targetName(scan.target)}-${scan.id}.json`; anchor.click(); URL.revokeObjectURL(url); }
}
