import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { PocketBaseService } from '../services/pocketbase.service';
import { ThemeService } from '../services/theme.service';

@Component({ selector: 'wg-settings', imports: [AppSidebarComponent, FormsModule], template: `
  <div class="app-layout"><wg-app-sidebar /><main class="app-main settings-page"><header class="app-header"><div><span class="app-breadcrumb">WORKSPACE / SETTINGS</span><h1>Workspace settings</h1><p>Local display preferences and the safety boundaries applied to every investigation.</p></div>@if (saved()) { <span class="saved-state">✓ Preferences saved</span> }</header>
  <section class="settings-grid"><article class="panel settings-card"><div class="panel-heading"><div><span class="section-index">APPEARANCE</span><h2>Interface theme</h2></div></div><p>Use the same evidence colors in a light or dark operating environment.</p><div class="theme-options"><button type="button" [class.selected]="theme.theme() === 'dark'" (click)="theme.set('dark')"><span class="theme-preview dark"><i></i><i></i><i></i></span><strong>Dark</strong><small>Low-light operations</small></button><button type="button" [class.selected]="theme.theme() === 'light'" (click)="theme.set('light')"><span class="theme-preview light"><i></i><i></i><i></i></span><strong>Light</strong><small>Daylight review</small></button></div></article>
  <article class="panel settings-card"><div class="panel-heading"><div><span class="section-index">DEFAULT OBSERVATION</span><h2>Investigation policy</h2></div></div><label class="setting-field"><span>Default depth<small>Controls the bounded tool budget for new requests.</small></span><select [(ngModel)]="depth"><option value="standard">Standard · adaptive reconnaissance</option><option value="light">Light · essential checks</option></select></label><label class="setting-field"><span>Time display<small>Choose how timestamps appear in this browser.</small></span><select [(ngModel)]="timeMode"><option value="local">Local time</option><option value="utc">UTC</option></select></label><button class="button primary compact" type="button" (click)="save()">Save preferences</button></article>
  <article class="panel settings-card boundary-card"><div class="panel-heading"><div><span class="section-index">ENFORCED BOUNDARIES</span><h2>Safety policy</h2></div><span class="state-pill" data-state="healthy">active</span></div><ul class="boundary-list"><li><i>✓</i><span><strong>Authorized roots only</strong><small>Tool calls cannot escape the approved domain scope.</small></span></li><li><i>✓</i><span><strong>No exploitation</strong><small>No credentials, payloads, evasion, or state-changing requests.</small></span></li><li><i>✓</i><span><strong>Private networks blocked</strong><small>Loopback and private addresses are rejected unless explicitly allowed.</small></span></li><li><i>✓</i><span><strong>Action budget</strong><small>Each investigation has a hard maximum number of tool calls.</small></span></li></ul></article>
  <article class="panel settings-card"><div class="panel-heading"><div><span class="section-index">ACCOUNT</span><h2>Current session</h2></div></div><dl class="fact-list"><div><dt>Email</dt><dd>{{ db.user()?.['email'] || 'Unknown' }}</dd></div><div><dt>Role</dt><dd>{{ db.user()?.['role'] || 'member' }}</dd></div><div><dt>Access</dt><dd>Administrator issued</dd></div></dl><button class="button secondary compact" type="button" (click)="signOut()">Sign out</button></article></section>
  </main></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class SettingsComponent {
  protected readonly theme = inject(ThemeService); protected readonly db = inject(PocketBaseService); protected readonly saved = signal(false); protected depth = localStorage.getItem('wellguard-scan-depth') || 'standard'; protected timeMode = localStorage.getItem('wellguard-time-mode') || 'local';
  protected save(): void { localStorage.setItem('wellguard-scan-depth', this.depth); localStorage.setItem('wellguard-time-mode', this.timeMode); this.saved.set(true); setTimeout(() => this.saved.set(false), 2200); }
  protected signOut(): void { this.db.signOut(); location.assign('/'); }
}
