import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { InfrastructureGraphComponent } from '../components/infrastructure-graph.component';
import { AgentActionRecord, AssetRecord, AssetRelationRecord, CertificateTransparencyRecord, Finding, Scan, Target, TlsObservation } from '../models';
import { PocketBaseService } from '../services/pocketbase.service';

@Component({ selector: 'wg-surface', imports: [AppSidebarComponent, InfrastructureGraphComponent, FormsModule, RouterLink, DatePipe], template: `
  <div class="app-layout"><wg-app-sidebar /><main class="app-main surface-page"><header class="app-header"><div><span class="app-breadcrumb">POSTURE / INFRASTRUCTURE</span><h1>Infrastructure topology</h1><p>Follow the retained path from authorized host to server, server port, routed domain, and observed service.</p></div><div class="surface-selectors"><label class="target-select"><span>Target</span><select [ngModel]="selectedId()" (ngModelChange)="selectTarget($event)"><option value="portfolio">Portfolio · latest state</option>@for (target of targets(); track target.id) { <option [value]="target.id">{{ target.hostname }}</option> }</select></label>@if (selectedId() === 'portfolio' && portfolioTags().length) { <label class="target-select"><span>Tag</span><select [ngModel]="portfolioTag()" (ngModelChange)="selectPortfolioTag($event)"><option value="all">All tags</option>@for (tag of portfolioTags(); track tag) { <option [value]="tag">{{ tag }}</option> }</select></label> }</div></header>
  @if (error()) { <div class="error-banner"><strong>Surface unavailable</strong><span>{{ error() }}</span></div> }
  @if (selectedId() !== 'portfolio' && completedScans().length) { <section class="snapshot-rail panel"><div class="snapshot-identity"><span class="section-index">OBSERVATION HISTORY</span><strong>{{ selectedSnapshotDate() | date:'medium' }}</strong><small>{{ snapshotIndex() + 1 }} of {{ completedScans().length }} retained snapshots @if (snapshotIndex() === completedScans().length - 1) { · latest }</small></div><div class="time-rail"><button type="button" aria-label="Previous snapshot" [disabled]="snapshotIndex() === 0" (click)="selectSnapshot(snapshotIndex() - 1)">←</button><input type="range" min="0" [max]="completedScans().length - 1" step="1" [ngModel]="snapshotIndex()" (ngModelChange)="selectSnapshot($event)" aria-label="Historical topology snapshot"><button type="button" aria-label="Next snapshot" [disabled]="snapshotIndex() === completedScans().length - 1" (click)="selectSnapshot(snapshotIndex() + 1)">→</button></div><label class="compare-switch" [class.disabled]="!previousSnapshot()"><input type="checkbox" [checked]="comparisonEnabled()" [disabled]="!previousSnapshot()" (change)="toggleComparison()"><span><strong>Compare to previous</strong><small>@if (previousSnapshot()) { Overlay new, changed and not observed assets } @else { A prior snapshot is required }</small></span></label><a routerLink="/app/changes" [queryParams]="{target:selectedId()}">Review changes →</a></section> }
  @if (target(); as item) {
    <section class="panel topology-panel expanded"><div class="panel-heading"><div><span class="section-index">{{ selectedId() === 'portfolio' ? 'PORTFOLIO · LATEST OBSERVED STATE' : comparisonEnabled() ? 'VISUAL CHANGE OVERLAY' : snapshotIndex() === completedScans().length - 1 ? 'CURRENT OBSERVED ARCHITECTURE' : 'HISTORICAL OBSERVATION' }}</span><h2>{{ item.hostname }}</h2></div><div class="panel-actions"><span class="evidence-count">One port node per observed machine · hover traces the path</span>@if (selectedId() !== 'portfolio') { <a [routerLink]="['/app/targets', item.id]">Target record →</a> }</div></div><wg-infrastructure-graph [target]="item" [findings]="findings()" [tls]="tls()" [actions]="actions()" [assets]="assets()" [relations]="relations()" [previousAssets]="previousAssets()" [previousRelations]="previousRelations()" [comparisonEnabled]="comparisonEnabled()" /></section>
    @if (domainIntelligence(); as intel) {
      <section class="domain-intelligence-grid">
        <article class="panel intelligence-card identity-ledger"><div class="panel-heading"><div><span class="section-index">AUTHORITATIVE IDENTITY</span><h2>Domain registration</h2></div>@if (intel.source) { <a [href]="intel.source" target="_blank" rel="noopener">RDAP evidence ↗</a> }</div><dl class="fact-list"><div><dt>Registrar</dt><dd>{{ intel.registrar }}</dd></div><div><dt>Registered</dt><dd>{{ intel.registered ? (intel.registered | date:'mediumDate') : 'Not published' }}</dd></div><div><dt>Expires</dt><dd>{{ intel.expires ? (intel.expires | date:'mediumDate') : 'Not published' }}</dd></div><div><dt>Public contacts</dt><dd>{{ intel.contacts.join(', ') || 'None published / redacted' }}</dd></div><div><dt>TLS identity email</dt><dd>{{ intel.tlsEmails.join(', ') || 'None in live certificate' }}</dd></div></dl><p class="evidence-note"><span>BOUNDARY</span>Private or redacted registration data remains undisclosed.</p></article>
        <article class="panel intelligence-card dns-ledger"><div class="panel-heading"><div><span class="section-index">PUBLIC CONTROL PLANE</span><h2>DNS &amp; mail posture</h2></div><span class="state-pill" [attr.data-state]="intel.dnssec ? 'healthy' : 'warning'">DNSSEC {{ intel.dnssec ? 'on' : 'not seen' }}</span></div><div class="dns-route"><span>NS</span><p>{{ intel.nameservers.join(' · ') || 'No nameservers retained' }}</p></div><div class="dns-route"><span>MX</span><p>{{ intel.mx.join(' · ') || 'No mail exchangers retained' }}</p></div><div class="policy-cells"><div><small>SPF</small><strong>{{ intel.spf ? 'Published' : 'Not seen' }}</strong></div><div><small>DMARC</small><strong>{{ intel.dmarc }}</strong></div><div><small>CAA</small><strong>{{ intel.caa ? 'Constrained' : 'Not seen' }}</strong></div></div><p class="evidence-note"><span>EVIDENCE</span>Direct DNS resolution from the most recent retained posture inspection.</p></article>
      </section>
    }
    @if (certificateInventory(); as inventory) {
      <section class="panel certificate-inventory"><div class="panel-heading"><div><span class="section-index">PUBLIC CERTIFICATE HISTORY</span><h2>{{ inventory.total }} certificate-transparency records</h2></div><span class="evidence-count">Source · {{ inventory.source }}</span></div>
        @if (inventory.certificates.length) { <div class="certificate-table"><div class="certificate-head"><span>Common name / names</span><span>Issuer</span><span>Validity</span><span>Record</span></div>@for (certificate of inventory.certificates; track $index) { <details class="certificate-row"><summary><span><strong>{{ certificate.commonName || certificate.names[0] || 'Unnamed certificate' }}</strong><small>{{ certificate.names.length }} DNS name{{ certificate.names.length === 1 ? '' : 's' }}</small></span><span>{{ issuer(certificate.issuerName) }}</span><span><strong>{{ certificate.notAfter | date:'mediumDate' }}</strong><small>{{ certificate.notBefore | date:'mediumDate' }} → {{ certificate.notAfter | date:'mediumDate' }}</small></span><b>Evidence ↓</b></summary><div><dl><div><dt>All certificate names</dt><dd>{{ certificate.names.join(', ') || 'Not retained' }}</dd></div><div><dt>Full issuer</dt><dd>{{ certificate.issuerName || 'Not retained' }}</dd></div><div><dt>Issuer CA identifier</dt><dd>{{ certificate.issuerCaId ?? 'Not returned' }}</dd></div><div><dt>Serial number</dt><dd>{{ certificate.serialNumber || 'Not retained' }}</dd></div><div><dt>Matching entries</dt><dd>{{ certificate.resultCount || 1 }}</dd></div></dl><p><span>EVIDENCE</span>Public certificate-transparency record {{ certificate.id }} returned by {{ inventory.source }}.</p></div></details> }</div> }
        @else { <div class="empty-state"><strong>This older scan retained the count, but not individual records.</strong><span>Run a new investigation to retain and display each certificate record and its names, issuer, validity, serial, and log timestamp.</span></div> }
      </section>
    }
    <div class="map-notice"><span>ABOUT INFERENCE</span><p>Dashed or unknown details are deliberate. When a CDN conceals the origin, Wellguard will not present edge geolocation or open edge ports as facts about your server.</p></div>
  }
  </main></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class SurfaceComponent implements OnInit {
  private readonly db = inject(PocketBaseService); private readonly route = inject(ActivatedRoute); protected readonly targets = signal<Target[]>([]); protected readonly selectedId = signal(''); protected readonly portfolioTag = signal('all'); protected readonly findings = signal<Finding[]>([]); protected readonly tls = signal<TlsObservation | null>(null); protected readonly actions = signal<AgentActionRecord[]>([]); protected readonly assets = signal<AssetRecord[]>([]); protected readonly relations = signal<AssetRelationRecord[]>([]); protected readonly previousAssets = signal<AssetRecord[]>([]); protected readonly previousRelations = signal<AssetRelationRecord[]>([]); protected readonly scans = signal<Scan[]>([]); protected readonly selectedScanId = signal(''); protected readonly comparisonEnabled = signal(false); protected readonly error = signal('');
  protected readonly portfolioTags = computed(() => [...new Set(this.targets().flatMap((target) => target.tags))].sort());
  protected readonly target = computed<Target | null>(() => this.selectedId() === 'portfolio' ? { id: 'portfolio', workspace: this.db.activeWorkspaceId(), name: 'Authorized portfolio', hostname: this.portfolioTag() === 'all' ? 'Authorized portfolio' : `Portfolio · ${this.portfolioTag()}`, hostHints: [], authorizedHosts: this.targets().flatMap((target) => target.authorizedHosts), authorizationStatus: 'admin_override', status: 'observed', lastScanAt: '', assetCount: this.assets().length, findingCount: this.findings().length, posture: 100, criticality: 'standard', tags: [] } : this.targets().find((x) => x.id === this.selectedId()) || null);
  protected readonly completedScans = computed(() => this.scans().filter((scan) => scan.status === 'completed').sort((a, b) => Date.parse(a.completedAt || a.created) - Date.parse(b.completedAt || b.created)));
  protected readonly snapshotIndex = computed(() => Math.max(0, this.completedScans().findIndex((scan) => scan.id === this.selectedScanId())));
  protected readonly selectedSnapshot = computed(() => this.completedScans()[this.snapshotIndex()] || null);
  protected readonly previousSnapshot = computed(() => this.snapshotIndex() > 0 ? this.completedScans()[this.snapshotIndex() - 1] : null);
  private loadSequence = 0;
  protected readonly certificateInventory = computed(() => {
    const action = this.actions().filter((item) => item.tool === 'inspect_certificate_transparency').at(-1);
    if (!action) return null;
    try {
      const data = JSON.parse(action.summary) as { source?: string; certificateCount?: number; certificates?: CertificateTransparencyRecord[] };
      return { source: data.source || 'certificate transparency', total: Number(data.certificateCount || data.certificates?.length || 0), certificates: data.certificates || [] };
    } catch { return null; }
  });
  protected readonly domainIntelligence = computed(() => {
    const parse = <T>(tool: string): T | null => {
      const action = this.actions().filter((item) => item.tool === tool).at(-1);
      try { return action ? JSON.parse(action.summary) as T : null; } catch { return null; }
    };
    const registration = parse<{ source?: string; registrar?: { names?: string[]; organizations?: string[] }; events?: Record<string, string>; publicEmails?: string[] }>('inspect_domain_registration');
    const dns = parse<{ nameservers?: string[]; mx?: Array<{ exchange?: string; priority?: number }>; caa?: unknown[]; emailSecurity?: { spf?: string[]; dmarcPolicy?: string }; dnssec?: { enabled?: boolean } }>('inspect_dns_posture');
    if (!registration && !dns && !this.tls()?.certificateEmails?.length) return null;
    return {
      source: registration?.source || '', registrar: registration?.registrar?.organizations?.[0] || registration?.registrar?.names?.[0] || 'Not published',
      registered: registration?.events?.['registration'] || '', expires: registration?.events?.['expiration'] || '', contacts: registration?.publicEmails || [],
      tlsEmails: this.tls()?.certificateEmails || [], nameservers: dns?.nameservers || [],
      mx: (dns?.mx || []).map((item) => `${item.priority ?? '–'} ${item.exchange || ''}`.trim()), dnssec: Boolean(dns?.dnssec?.enabled),
      spf: Boolean(dns?.emailSecurity?.spf?.length), dmarc: dns?.emailSecurity?.dmarcPolicy || 'Not seen', caa: Boolean(dns?.caa?.length)
    };
  });
  ngOnInit(): void { void this.db.targets().then((items) => { this.targets.set(items); const requested = this.route.snapshot.queryParamMap.get('target'); const id = requested === 'portfolio' ? 'portfolio' : items.some((item) => item.id === requested) ? requested! : items[0]?.id || ''; this.selectedId.set(id); this.comparisonEnabled.set(this.route.snapshot.queryParamMap.get('compare') === '1'); return this.loadTarget(this.route.snapshot.queryParamMap.get('scan') || ''); }).catch((e) => this.error.set(e instanceof Error ? e.message : 'Could not load surface.')); }
  protected selectTarget(id: string): void { this.selectedId.set(id); this.comparisonEnabled.set(false); void this.loadTarget(); }
  protected selectPortfolioTag(tag: string): void { this.portfolioTag.set(tag); void this.loadPortfolio(); }
  private async loadTarget(requestedScan = ''): Promise<void> { const id = this.selectedId(); if (!id) return; if (id === 'portfolio') { await this.loadPortfolio(); return; } try { const scans = await this.db.scans(id); this.scans.set(scans); const completed = scans.filter((scan) => scan.status === 'completed').sort((a, b) => Date.parse(a.completedAt || a.created) - Date.parse(b.completedAt || b.created)); this.selectedScanId.set(completed.some((scan) => scan.id === requestedScan) ? requestedScan : completed.at(-1)?.id || scans[0]?.id || ''); if (!this.previousSnapshot()) this.comparisonEnabled.set(false); await this.loadEvidence(); } catch (e) { this.error.set(e instanceof Error ? e.message : 'Could not load evidence.'); } }
  private async loadPortfolio(): Promise<void> {
    const sequence = ++this.loadSequence; const included = this.targets().filter((target) => this.portfolioTag() === 'all' || target.tags.includes(this.portfolioTag()));
    try {
      const snapshots = await Promise.all(included.map(async (target) => { const scans = await this.db.scans(target.id); const latest = scans.filter((scan) => scan.status === 'completed').sort((a, b) => Date.parse(b.completedAt || b.created) - Date.parse(a.completedAt || a.created))[0]; if (!latest) return null; const [assets, relations, findings] = await Promise.all([this.db.assets(target.id, latest.id), this.db.assetRelations(target.id, latest.id), this.db.findings(target.id)]); return { target, latest, assets, relations, findings: findings.filter((finding) => finding.scan === latest.id || finding.observations.some((observation) => observation.scan === latest.id)) }; }));
      if (sequence !== this.loadSequence) return;
      const assetMap = new Map<string, AssetRecord>(); const relationMap = new Map<string, AssetRelationRecord>(); const findings: Finding[] = [];
      const stateRank = { risk: 4, warning: 3, unknown: 2, observed: 1, healthy: 0 } as Record<string, number>;
      for (const snapshot of snapshots) if (snapshot) {
        findings.push(...snapshot.findings);
        for (const asset of snapshot.assets) { const tagged = { ...asset, target: 'portfolio', scan: 'latest', details: [{ label: 'Portfolio target', value: snapshot.target.hostname, evidence: `Latest completed observation ${snapshot.latest.completedAt || snapshot.latest.created}.`, basis: 'owner_confirmed' as const, confidence: 100 }, ...asset.details] }; const existing = assetMap.get(asset.key); if (!existing || stateRank[tagged.state] > stateRank[existing.state]) assetMap.set(asset.key, tagged); }
        for (const relation of snapshot.relations) { const key = `${relation.fromKey}|${relation.toKey}|${relation.type}`; if (!relationMap.has(key)) relationMap.set(key, { ...relation, id: key, key, target: 'portfolio', scan: 'latest' }); }
      }
      this.scans.set([]); this.selectedScanId.set(''); this.findings.set(findings); this.tls.set(null); this.actions.set([]); this.assets.set([...assetMap.values()]); this.relations.set([...relationMap.values()]); this.previousAssets.set([]); this.previousRelations.set([]); this.comparisonEnabled.set(false);
    } catch (e) { if (sequence === this.loadSequence) this.error.set(e instanceof Error ? e.message : 'Could not build the portfolio map.'); }
  }
  protected selectSnapshot(index: number | string): void { const safe = Math.max(0, Math.min(this.completedScans().length - 1, Number(index))); this.selectedScanId.set(this.completedScans()[safe]?.id || ''); if (!this.previousSnapshot()) this.comparisonEnabled.set(false); void this.loadEvidence(); }
  protected toggleComparison(): void { if (!this.previousSnapshot()) return; this.comparisonEnabled.update((value) => !value); void this.loadEvidence(); }
  protected async loadEvidence(): Promise<void> { const id = this.selectedId(); const scanId = this.selectedScanId(); if (!id || !scanId) return; const sequence = ++this.loadSequence; try { const previousId = this.previousSnapshot()?.id; const [allFindings, tls, actions, assets, relations, previousAssets, previousRelations] = await Promise.all([this.db.findings(id), this.db.tls(id, this.target()?.hostname, scanId), this.db.agentActions({ targetId: id, scanId }), this.db.assets(id, scanId), this.db.assetRelations(id, scanId), previousId ? this.db.assets(id, previousId) : Promise.resolve([]), previousId ? this.db.assetRelations(id, previousId) : Promise.resolve([])]); if (sequence !== this.loadSequence) return; const findings = allFindings.filter((finding) => finding.scan === scanId || finding.observations.some((observation) => observation.scan === scanId)); this.findings.set(findings); this.tls.set(tls); this.actions.set(actions); this.assets.set(assets); this.relations.set(relations); this.previousAssets.set(previousAssets); this.previousRelations.set(previousRelations); } catch (e) { if (sequence === this.loadSequence) this.error.set(e instanceof Error ? e.message : 'Could not load evidence.'); } }
  protected issuer(value: string): string { return value.match(/(?:^|,)\s*O=([^,]+)/)?.[1] || value.match(/(?:^|,)\s*CN=([^,]+)/)?.[1] || value || 'Unknown issuer'; }
  protected selectedSnapshotDate(): string { const snapshot = this.selectedSnapshot(); return snapshot?.completedAt || snapshot?.created || ''; }
}
