import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AppSidebarComponent } from '../components/app-sidebar.component';
import { InfrastructureGraphComponent } from '../components/infrastructure-graph.component';
import { AgentActionRecord, AssetRecord, AssetRelationRecord, Finding, Scan, Target, TlsObservation } from '../models';
import { PocketBaseService } from '../services/pocketbase.service';

@Component({
  selector: 'wg-target-detail', imports: [AppSidebarComponent, InfrastructureGraphComponent, DatePipe, RouterLink],
  template: `
    <div class="app-layout"><wg-app-sidebar /><main class="app-main">
      <header class="app-header"><div><a class="app-breadcrumb" routerLink="/app/targets">TARGETS / DETAIL</a><h1>{{ target()?.hostname || 'Loading target…' }}</h1><p>{{ target()?.name }}</p></div><div class="header-actions"><span class="authorization-badge"><i></i>{{ target()?.authorizationStatus === 'admin_override' ? 'Admin approved' : 'Ownership verified' }}</span><button class="button primary compact" type="button" (click)="scan()" [disabled]="scanState() !== 'idle'">{{ scanLabel() }} <span>◎</span></button></div></header>
      @if (error()) { <div class="error-banner"><strong>Target data unavailable</strong><span>{{ error() }}</span></div> }
      @if (target(); as item) {
        <nav class="subnav"><a [routerLink]="[]" fragment="map">Surface map</a><a [routerLink]="[]" fragment="findings">Findings <b>{{ findings().length }}</b></a><a [routerLink]="[]" fragment="tls">TLS</a><a routerLink="/app/traces" [queryParams]="{ target: item.id }">Agent trace</a><a routerLink="/app/reports" [queryParams]="{ target: item.id }">Reports</a></nav>
        <section class="target-facts"><div><small>STATUS</small><strong><i class="live-dot"></i>{{ item.status }}</strong></div><div><small>POSTURE</small><strong>{{ item.posture }} / 100</strong></div><div><small>LAST SCAN</small><strong>{{ item.lastScanAt | date:'MMM d, HH:mm:ss' }}</strong></div><div><small>RETAINED TOOLS</small><strong>{{ actions().length }}</strong></div><div><small>SCAN HISTORY</small><strong>{{ scans().length }}</strong></div></section>
        <section class="panel topology-panel" id="map"><div class="panel-heading"><div><span class="section-index">CLICK ANY ASSET OR PATH</span><h2>Observed infrastructure</h2></div><span class="evidence-count">Evidence-linked model</span></div><wg-infrastructure-graph [target]="item" [findings]="findings()" [tls]="tls()" [actions]="actions()" [assets]="assets()" [relations]="relations()" /></section>
        <section class="target-detail-grid">
          <article class="panel" id="findings"><div class="panel-heading"><div><span class="section-index">FINDINGS</span><h2>Evidence and action</h2></div><a routerLink="/app/findings">Open register →</a></div><div class="finding-cards">@for (finding of findings(); track finding.id) { <article class="finding-card"><header><span class="severity-label" [attr.data-severity]="finding.severity">{{ finding.severity }}</span><span>{{ finding.confidence }}% confidence</span></header><h3>{{ finding.title }}</h3>@if (finding.weaknessIds.length || finding.cveIds.length) { <div class="identifier-strip">@for (id of finding.weaknessIds; track id) { <span data-kind="cwe">{{ id }}</span> } @for (id of finding.cveIds; track id) { <span data-kind="cve">{{ id }}</span> }</div> }<p>{{ finding.summary }}</p><details><summary>Evidence ({{ finding.evidence.length }})</summary><ul>@for (item of finding.evidence; track item) { <li>{{ item }}</li> }</ul></details><div class="remediation"><small>RECOMMENDED ACTION</small><p>{{ finding.remediation || 'Review this exposure and reduce public access when it is not explicitly required.' }}</p></div></article> } @empty { <div class="empty-state">No findings retained for this target.</div> }</div></article>
          <aside class="panel tls-card" id="tls"><div class="panel-heading"><div><span class="section-index">TRANSPORT IDENTITY</span><h2>TLS certificate</h2></div><span class="state-pill" [attr.data-state]="tls()?.valid ? 'healthy' : 'warning'">{{ tls()?.valid ? 'Valid' : 'Unknown' }}</span></div>@if (tls(); as certificate) { <div class="tls-score"><strong>{{ certificate.daysRemaining }}</strong><span>days until expiry</span></div><dl class="fact-list"><div><dt>Issuer</dt><dd>{{ certificate.issuer }}</dd></div><div><dt>Protocol</dt><dd>{{ certificate.protocol }}</dd></div><div><dt>Cipher</dt><dd>{{ certificate.cipher || 'Not retained' }}</dd></div><div><dt>Valid until</dt><dd>{{ certificate.validTo | date:'MMM d, y, HH:mm' }}</dd></div><div><dt>Names</dt><dd>{{ certificate.subjectAltNames.join(', ') }}</dd></div><div><dt>Public email</dt><dd>{{ certificate.certificateEmails?.join(', ') || 'None in certificate' }}</dd></div></dl><p class="evidence-note"><span>EVIDENCE</span>Values come from a direct, hostname-validated TLS handshake.</p> } @else { <div class="empty-state">No TLS observation is available.</div> }</aside>
        </section>
      }
    </main></div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TargetDetailComponent implements OnInit {
  private readonly db = inject(PocketBaseService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  protected readonly target = signal<Target | null>(null); protected readonly findings = signal<Finding[]>([]); protected readonly tls = signal<TlsObservation | null>(null); protected readonly actions = signal<AgentActionRecord[]>([]); protected readonly assets = signal<AssetRecord[]>([]); protected readonly relations = signal<AssetRelationRecord[]>([]); protected readonly scans = signal<Scan[]>([]); protected readonly scanState = signal<'idle'|'requesting'|'queued'>('idle'); protected readonly error = signal('');
  protected readonly scanLabel = () => ({ idle: 'Run observation', requesting: 'Queueing…', queued: 'Queued' })[this.scanState()];
  ngOnInit(): void { void this.load(); }
  private async load(): Promise<void> { const id = this.route.snapshot.paramMap.get('id') || ''; try { const targets = await this.db.targets(); const target = targets.find((x) => x.id === id) || null; const scans = await this.db.scans(id); const latest = scans.find((scan) => scan.status === 'completed') || scans[0]; const scanId = latest?.id; const [findings, tls, actions, assets, relations] = await Promise.all([this.db.findings(id, scanId), this.db.tls(id, target?.hostname), this.db.agentActions({ targetId: id, scanId }), this.db.assets(id, scanId), this.db.assetRelations(id, scanId)]); this.target.set(target); this.findings.set(findings); this.tls.set(tls); this.actions.set(actions); this.assets.set(assets); this.relations.set(relations); this.scans.set(scans); } catch (e) { this.error.set(e instanceof Error ? e.message : 'Could not load target.'); } }
  protected async scan(): Promise<void> { const target = this.target(); if (!target) return; this.scanState.set('requesting'); try { const requestId = await this.db.requestScan(target.id); this.scanState.set('queued'); await this.router.navigate(['/app/investigations', requestId]); } catch { this.scanState.set('idle'); } }
}
